feat: add check-health.yml
CircleCI-Public/aws-health-orb pull request #1
Opened 2022-10-03 22:24 UTC by brivu

This PR adds the `check-health.yml` to the `AWS Health` Orb. It merges into the `alpha` branch. Once the orb is complete and ready for a new release, the `alpha` branch will be merged into main.

2022-10-03 22:58 UTC, felicianotech requested changes
Just minor spelling corrections needed.

2022-10-03 22:58 UTC, felicianotech commented on src/commands/check-health.yml
> +  no issues are dectected. If the max attempts have been reached, the commad will fail.
command*

2022-10-03 22:58 UTC, felicianotech commented on src/commands/check-health.yml
> +      The AWS region to be checked for issues. It defaults to AWS_REGION that's set as an environment varaible
variable*

2022-10-03 23:00 UTC, JalexChen approved these changes

2022-10-04 14:06 UTC, KyleTryon requested changes

2022-10-04 14:06 UTC, KyleTryon commented on .circleci/test-deploy.yml
>        - checkout
```suggestion
```

Checkout is not needed for this

2022-10-04 18:49 UTC, merged